CREATE TABLE user_places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    place_key VARCHAR(180) NOT NULL,
    source_id VARCHAR(140) NOT NULL,
    category VARCHAR(50) NOT NULL,
    name VARCHAR(200) NOT NULL,
    address VARCHAR(500),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    favorite BOOLEAN NOT NULL DEFAULT FALSE,
    saved_at TIMESTAMP(6),
    last_viewed_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_user_places_user_key UNIQUE (user_id, place_key),
    CONSTRAINT ck_user_places_seoul_coordinates
        CHECK (latitude BETWEEN 37.3 AND 37.8 AND longitude BETWEEN 126.6 AND 127.3)
);

CREATE INDEX idx_user_places_favorites
    ON user_places (user_id, saved_at DESC) WHERE favorite = TRUE;
CREATE INDEX idx_user_places_recent
    ON user_places (user_id, last_viewed_at DESC) WHERE last_viewed_at IS NOT NULL;

CREATE TABLE saved_zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    label VARCHAR(40) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    radius_meters INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_saved_zones_user_label UNIQUE (user_id, label),
    CONSTRAINT ck_saved_zones_radius CHECK (radius_meters BETWEEN 100 AND 20000),
    CONSTRAINT ck_saved_zones_seoul_coordinates
        CHECK (latitude BETWEEN 37.3 AND 37.8 AND longitude BETWEEN 126.6 AND 127.3)
);

CREATE INDEX idx_saved_zones_user ON saved_zones (user_id, created_at DESC);

CREATE TABLE alert_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    zone_id BIGINT NOT NULL REFERENCES saved_zones(id) ON DELETE CASCADE,
    alert_type VARCHAR(40) NOT NULL,
    active_days VARCHAR(32) NOT NULL,
    active_start TIME,
    active_end TIME,
    quiet_start TIME,
    quiet_end TIME,
    cooldown_minutes INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    last_triggered_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_alert_subscriptions_user_zone_type UNIQUE (user_id, zone_id, alert_type),
    CONSTRAINT ck_alert_subscriptions_cooldown
        CHECK (cooldown_minutes BETWEEN 15 AND 10080)
);

CREATE INDEX idx_alert_subscriptions_due
    ON alert_subscriptions (user_id, active, last_triggered_at);

ALTER TABLE notification_histories
    ADD COLUMN subscription_id BIGINT REFERENCES alert_subscriptions(id) ON DELETE SET NULL,
    ADD COLUMN reason VARCHAR(500),
    ADD COLUMN deep_link VARCHAR(500),
    ADD COLUMN data_observed_at TIMESTAMP(6),
    ADD COLUMN provider_status VARCHAR(40) NOT NULL DEFAULT 'IN_APP_CREATED',
    ADD COLUMN dedup_key VARCHAR(220);

CREATE UNIQUE INDEX uq_notification_histories_dedup_key
    ON notification_histories (dedup_key) WHERE dedup_key IS NOT NULL;
